name: Robot Tests
on: [pull_request, push, workflow_dispatch]

jobs:
  robot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m http.server 8080 --directory . &

      - name: Run tests
        run: |
          echo "event_name=${{ github.event_name }}"
          TEST_DIR=tests/e2e
          TAG=nightly

          if [ "${{ github.event_name }}" = "pull_request" ]; then TAG=smoke; fi
          if [ "${{ github.event_name }}" = "push" ]; then TAG=regression; fi

          robot -d results -v BASE_URL:http://localhost:8080 -v HEADLESS:true -i "$TAG" "$TEST_DIR"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: results
